services:
  labeler:
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: unless-stopped
    env_file:
      - /games-industry-labeler/.env
    volumes:
      - type: bind
        source: /games-industry-labeler/database
        target: /etc/database
